checks:
  php: true

filter:
  paths: ["src/*"]

tools:
  external_code_coverage: 
    timeout: 600
  php_code_coverage: true
  php_sim: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  php_cpd: true
  sensiolabs_security_checker: true